# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c90887fe3735d192fcc7113c78df789dcbee418f800eae93e9f1bf3d72b59c3ae65ab5f8bcd5b8331e93aa5514ec3cfcd69811d55d3b8ea0eb1baabf885a78

test:
  secret_key_base: 66170034e686dde14566a004ae06a1d5659da022415b744bbe972a52052dde2e4fbdbc2207b6b53d6b32107415928a8f94ee1eedd02754108515653bed8cc47f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a9dbde4cb8054d5427ca1366015cdd1bb642b1dd1e425c3081f1333902ce6147a0c4b9c346650f19a72613460ccffac3e4c555aaead910daf8be9b03af9eaa27
